
make up:
  cd infrastructure && docker-compose up -d

make down:
  cd infrastructure && docker-compose down

make logs:
  cd infrastructure && docker-compose logs -f

make ps:
  cd infrastructure && docker-compose ps
  
  # Очистка Kafka кластера
clean-kafka-cluster:
  cd infrastructure && docker-compose rm -f zookeeper kafka1 kafka2 kafka3
  cd infrastructure && docker-compose down -v zookeeper kafka1 kafka2 kafka3